# Generated by Django 5.2 on 2025-04-15 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance', models.PositiveSmallIntegerField(verbose_name='Devamlılık (1-10)')),
                ('performance', models.PositiveSmallIntegerField(verbose_name='Performans (1-10)')),
                ('adaptation', models.PositiveSmallIntegerField(verbose_name='Uyum (1-10)')),
                ('technical_skills', models.PositiveSmallIntegerField(verbose_name='Teknik Yeterlilik (1-10)')),
                ('communication_skills', models.PositiveSmallIntegerField(verbose_name='İletişim (1-10)')),
                ('teamwork', models.PositiveSmallIntegerField(verbose_name='Takım Çalışması (1-10)')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Yorum')),
                ('average_rating', models.FloatField(editable=False, verbose_name='Ortalama Puan')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Onaylandı mı?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Değerlendirme',
                'verbose_name_plural': 'Değerlendirmeler',
            },
        ),
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=200, verbose_name='Staj Konusu')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('start_date', models.DateField(verbose_name='Başlangıç Tarihi')),
                ('end_date', models.DateField(verbose_name='Bitiş Tarihi')),
                ('status', models.CharField(choices=[('pending', 'Beklemede'), ('approved_by_company', 'Şirket Onayladı'), ('approved_by_admin', 'Admin Onayladı'), ('rejected', 'Reddedildi'), ('completed', 'Tamamlandı')], default='pending', max_length=20, verbose_name='Durum')),
                ('working_days', models.PositiveIntegerField(default=0, verbose_name='Çalışma Günü')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Staj',
                'verbose_name_plural': 'Stajlar',
            },
        ),
        migrations.CreateModel(
            name='InternshipDiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveIntegerField(verbose_name='Gün Numarası')),
                ('content', models.TextField(verbose_name='İçerik')),
                ('date', models.DateField(verbose_name='Tarih')),
                ('status', models.CharField(choices=[('draft', 'Taslak'), ('submitted', 'Gönderildi')], default='draft', max_length=10, verbose_name='Durum')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Staj Günlüğü',
                'verbose_name_plural': 'Staj Günlükleri',
            },
        ),
    ]
