# Generated by Django 5.2 on 2025-05-09 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customrole',
            options={'verbose_name': 'Rol', 'verbose_name_plural': 'Roller'},
        ),
    ]
